name: paytm_intent_mesh
description: Cross-platform Paytm Intent Mesh companion prototype.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^13.0.2
  qr_flutter: ^4.1.0
  record: ^6.1.2
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
